[project]
name = "SaludNow"
version = "1.0.0"
description = "Aplicación Salud Now"
dependencies = [
    "flet>=1.0.0",
    "flet-local-auth>=1.0.0",
    "requests",
    "SQLAlchemy",
    "pg8000",
    "python-jose",
    "urllib3"
]

[tool.flet]
permissions = ["biometric"]

[tool.flet.flutter.pubspec.dependencies]
local_auth = "^2.2.3"
