const veStates = <String>[
  'Amazonas',
  'Anzoátegui',
  'Apure',
  'Aragua',
  'Barinas',
  'Bolívar',
  'Carabobo',
  'Cojedes',
  'Delta Amacuro',
  'Dependencias Federales',
  'Distrito Capital',
  'Falcón',
  'Guárico',
  'La Guaira',
  'Lara',
  'Mérida',
  'Miranda',
  'Monagas',
  'Nueva Esparta',
  'Portuguesa',
  'Sucre',
  'Táchira',
  'Trujillo',
  'Yaracuy',
  'Zulia',
];

const medicalSpecialties = <String>[
  'Alergología e Inmunología Clínica',
  'Análisis Clínicos',
  'Anatomía Patológica',
  'Anestesiología',
  'Angiología',
  'Bioquímica Clínica',
  'Cardiología',
  'Cirugía Cardiovascular',
  'Cirugía General',
  'Cirugía Oral y Maxilofacial',
  'Cirugía Ortopédica',
  'Cirugía Pediátrica',
  'Cirugía Plástica, Estética y Reparadora',
  'Cirugía Torácica',
  'Cirugía Vascular',
  'Cirugía de la Mano',
  'Dermatología',
  'Endocrinología',
  'Farmacología Clínica',
  'Foniatría / Audiología',
  'Gastroenterología',
  'Genética Médica',
  'Geriatría',
  'Gerontología Médica',
  'Ginecología y Obstetricia',
  'Hematología',
  'Infectología',
  'Inmunología',
  'Medicina Familiar y Comunitaria (o Medicina General)',
  'Medicina Física y Rehabilitación',
  'Medicina Intensiva',
  'Medicina Interna',
  'Medicina Legal y Forense',
  'Medicina Nuclear',
  'Medicina Paliativa / Cuidados Paliativos',
  'Medicina Preventiva y Salud Pública',
  'Medicina de Emergencias y Urgencias',
  'Medicina del Deporte',
  'Medicina del Trabajo',
  'Microbiología y Parasitología',
  'Nefrología',
  'Neumología',
  'Neurocirugía',
  'Neurofisiología Clínica',
  'Neurología',
  'Oftalmología',
  'Oncología Médica',
  'Oncología Radioterápica',
  'Otorrinolaringología',
  'Pediatría',
  'Psiquiatría',
  'Radiodiagnóstico / Radiología',
  'Reumatología',
  'Traumatología',
  'Urología',
  'Áreas de Laboratorio y Soporte Técnico',
];
