const veStates = <String>[
  'Amazonas',
  'Anzoátegui',
  'Apure',
  'Aragua',
  'Barinas',
  'Bolívar',
  'Carabobo',
  'Cojedes',
  'Delta Amacuro',
  'Dependencias Federales',
  'Distrito Capital',
  'Falcón',
  'Guárico',
  'La Guaira',
  'Lara',
  'Mérida',
  'Miranda',
  'Monagas',
  'Nueva Esparta',
  'Portuguesa',
  'Sucre',
  'Táchira',
  'Trujillo',
  'Yaracuy',
  'Zulia',
];

const medicalSpecialties = <String>[
  'Alergología',
  'Anestesiología Dental',
  'Anestesiología y Reanimación',
  'Audiología',
  'Cardiología Hemodinámica y Electrofisiología',
  'Cirugía Cardiovascular',
  'Cirugía General y del Aparato Digestivo',
  'Cirugía Oral y Maxilofacial',
  'Cirugía Ortopédica y Traumatología',
  'Cirugía Pediátrica',
  'Cirugía Plástica, Estética y Reparadora',
  'Cirugía Torácica',
  'Dermatología Médico-Quirúrgica y Venereología',
  'Endodoncia',
  'Endocrinología y Nutrición',
  'Fisioterapia Avanzada',
  'Gastroenterología y Hepatología',
  'Genética Médica',
  'Geriatría',
  'Ginecología y Obstetricia',
  'Medicina Materno-Fetal',
  'Reproducción Asistida',
  'Hematología y Hemoterapia',
  'Infectología',
  'Medicina del Trabajo',
  'Medicina Familiar y Comunitaria',
  'Medicina Física y Rehabilitación',
  'Medicina Intensiva',
  'Medicina Interna',
  'Medicina Legal y Forense',
  'Medicina Nuclear',
  'Medicina Preventiva y Salud Pública',
  'Nefrología',
  'Neumonología',
  'Neurocirugía',
  'Neurología',
  'Neuropediatría',
  'Nutrición y Dietética',
  'Odontología de Salud Pública',
  'Odontología General',
  'Odontopediatría',
  'Oftalmología',
  'Oncología Médica',
  'Oncología Radioterápica',
  'Ortodoncia',
  'Otorrinolaringología',
  'Patología Oral y Maxilofacial',
  'Pediatría Neonatología',
  'Periodoncia',
  'Prostodoncia',
  'Psiquiatría Infanto-Juvenil',
  'Radiodiagnóstico',
  'Radiología Oral y Maxilofacial',
  'Reumatología',
  'Urología',
];
